// let a=10;
// try{
//       throw new Error("Error occured");
//       let a=10/0;
//     console.log(a);
// }
// catch(err){
//     console.log(err);
// }
// finally{
//     console.log("completed");
// }